export enum heroAnimations {
runDown = 'runDown',
runUp = 'runUp',
runRight = 'runRight',
runUpRight = 'runUpRight',
runDownRight = 'runDownRight',
swimDown = 'swimDown',
swimUp = 'swimUp',
swimRight = 'swimRight',
swimUpRight = 'swimUpRight',
swimDownRight = 'swimDownRight',
jumpDown = 'jumpDown',
jumpUp = 'jumpUp',
jumpRight = 'jumpRight',
jumpUpRight = 'jumpUpRight',
jumpDownRight = 'jumpDownRight',
climbUp = 'climbUp',
climbDown = 'climbDown',
climbRight = 'climbRight',
climbUpRight = 'climbUpRight',
climbDownRight = 'climbDownRight',
sitDowm = 'sitDowm'
}